### PR TITLE
unyt 1.0.5

### PR DESCRIPTION
**Pull request by ngoldbaum**

### CODE REVIEW

**Comment by ngoldbaum** [comment]
@conda-forge-admin please rerender

**Comment by ngoldbaum** [comment]
@ocefpaf suggested on twitter it's kosher to merge this without waiting for windows, so doing that.

**Comment by ocefpaf** [comment]
> @ocefpaf suggested on twitter it's kosher to merge this without waiting for windows, so doing that.

It is a bad advice in general :smiling_imp: but quite harmless in this case. (And we get `unyt` on Linux faster :wink:)

**Comment by ocefpaf** [comment]
Actually, look at the code it seems like this one can be `noarch` and built only once on CircleCI. That is much faster and gets the package out for all platforms with a single build. Do you want to try that @ngoldbaum?

**Comment by ngoldbaum** [comment]
Unfortunately it can't because we have python2-specific dependencies. Unless that changed since I set this up earlier in the summer?

**Comment by ocefpaf** [comment]
Nope, you are correct the `backports.functools_lru_cache  # [py27]` is a blocker.
(I was looking at the code for extensions and not the dependencies.)

**Comment by ngoldbaum** [comment]
I'm just sitting here eagerly awaiting python2.7 to go the way of the dodo

**Pull request merged**
